name: Docker Image CI

on:
  push:
    branches: [ "master", "feature_update_mutect_strelka_variant_callers" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: neoantigen-discovery-pipeline
      IMAGE_VERSION: latest

    steps:
    - uses: actions/checkout@v3
    
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "${{secrets.DOCKER_USER}}/$IMAGE_NAME:$IMAGE_VERSION"
    
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag ${{secrets.DOCKER_USER}}/$IMAGE_NAME-${GITHUB_REF#refs/heads/}:$IMAGE_VERSION
       
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/$IMAGE_NAME-${GITHUB_REF#refs/heads/}:$IMAGE_VERSION
      
